#!/bin/bash
set -e

# Posts Terraform plan output as a comment on Azure DevOps PR
# Usage: ./scripts/terraform-plan-comment.sh <plan_output_file>

PLAN_FILE=$1

if [ -z "$PLAN_FILE" ] || [ ! -f "$PLAN_FILE" ]; then
  echo "Usage: $0 <plan_output_file>"
  exit 1
fi

# Check required environment variables
if [ -z "$SYSTEM_ACCESSTOKEN" ]; then
  echo "Error: SYSTEM_ACCESSTOKEN not set. Make sure pipeline has 'Allow scripts to access the OAuth token' enabled."
  exit 1
fi

if [ -z "$SYSTEM_PULLREQUEST_PULLREQUESTID" ]; then
  echo "Not a PR build, skipping comment"
  exit 0
fi

# Azure DevOps API endpoint
ORG_URL="${SYSTEM_COLLECTIONURI}"
PROJECT="${SYSTEM_TEAMPROJECT}"
REPO_ID="${BUILD_REPOSITORY_ID}"
PR_ID="${SYSTEM_PULLREQUEST_PULLREQUESTID}"

API_URL="${ORG_URL}${PROJECT}/_apis/git/repositories/${REPO_ID}/pullRequests/${PR_ID}/threads?api-version=7.0"

# Read and truncate plan output if too long (Azure DevOps has limits)
PLAN_OUTPUT=$(cat "$PLAN_FILE")
MAX_LENGTH=60000
if [ ${#PLAN_OUTPUT} -gt $MAX_LENGTH ]; then
  PLAN_OUTPUT="${PLAN_OUTPUT:0:$MAX_LENGTH}

... (truncated, see pipeline logs for full output)"
fi

# Escape for JSON
PLAN_OUTPUT_ESCAPED=$(echo "$PLAN_OUTPUT" | jq -Rs .)

# Create comment body
COMMENT_BODY=$(cat <<EOF
## Terraform Plan Results

<details>
<summary>Show Plan Output</summary>

\`\`\`hcl
${PLAN_OUTPUT}
\`\`\`

</details>

> This plan was generated by Azure Pipelines.
> After merge, TF-Controller will run the actual apply with manual approval.
EOF
)

# Escape comment body for JSON
COMMENT_ESCAPED=$(echo "$COMMENT_BODY" | jq -Rs .)

# Create the PR comment thread
JSON_PAYLOAD=$(cat <<EOF
{
  "comments": [
    {
      "parentCommentId": 0,
      "content": ${COMMENT_ESCAPED},
      "commentType": 1
    }
  ],
  "status": 1
}
EOF
)

echo "Posting Terraform plan to PR #${PR_ID}..."

curl -s -X POST \
  -H "Authorization: Bearer ${SYSTEM_ACCESSTOKEN}" \
  -H "Content-Type: application/json" \
  -d "$JSON_PAYLOAD" \
  "$API_URL"

echo ""
echo "Plan posted to PR successfully"
