apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: interview-buddy-infra
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux/infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: interview-buddy
  targetNamespace: flux-system
